/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomManufacturingRouteImport } from './routes/custom-manufacturing'
import { Route as ManufacturingRouteImport } from './routes/manufacturing'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsCategoryRouteImport } from './routes/products.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomManufacturingRoute = CustomManufacturingRouteImport.update({
  id: '/custom-manufacturing',
  path: '/custom-manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturingRoute = ManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryRoute = ProductsCategoryRouteImport.update({
  id: '/products/$category',
  path: '/products/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom-manufacturing': typeof CustomManufacturingRoute
  '/manufacturing': typeof ManufacturingRoute
  '/quality': typeof QualityRoute
  '/wholesale': typeof WholesaleRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/industries/': typeof IndustriesIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom-manufacturing': typeof CustomManufacturingRoute
  '/manufacturing': typeof ManufacturingRoute
  '/quality': typeof QualityRoute
  '/wholesale': typeof WholesaleRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/industries': typeof IndustriesIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custom-manufacturing': typeof CustomManufacturingRoute
  '/manufacturing': typeof ManufacturingRoute
  '/quality': typeof QualityRoute
  '/wholesale': typeof WholesaleRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/industries/': typeof IndustriesIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/custom-manufacturing'
    | '/manufacturing'
    | '/quality'
    | '/wholesale'
    | '/industries/$slug'
    | '/products/$category'
    | '/industries/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/custom-manufacturing'
    | '/manufacturing'
    | '/quality'
    | '/wholesale'
    | '/industries/$slug'
    | '/products/$category'
    | '/industries'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/custom-manufacturing'
    | '/manufacturing'
    | '/quality'
    | '/wholesale'
    | '/industries/$slug'
    | '/products/$category'
    | '/industries/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomManufacturingRoute: typeof CustomManufacturingRoute
  ManufacturingRoute: typeof ManufacturingRoute
  QualityRoute: typeof QualityRoute
  WholesaleRoute: typeof WholesaleRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  ProductsCategoryRoute: typeof ProductsCategoryRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-manufacturing': {
      id: '/custom-manufacturing'
      path: '/custom-manufacturing'
      fullPath: '/custom-manufacturing'
      preLoaderRoute: typeof CustomManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturing': {
      id: '/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof ManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category': {
      id: '/products/$category'
      path: '/products/$category'
      fullPath: '/products/$category'
      preLoaderRoute: typeof ProductsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomManufacturingRoute: CustomManufacturingRoute,
  ManufacturingRoute: ManufacturingRoute,
  QualityRoute: QualityRoute,
  WholesaleRoute: WholesaleRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  ProductsCategoryRoute: ProductsCategoryRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
